PilaFacek/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('app/', include("orders.urls")),
    path('', RedirectView.as_view(url="https://pila-facek.cz")),
]

orders/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "orders"
urlpatterns = [
    # pages
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("r/<int:r_id>", views.r_info, name="r_info"),
    path("h/<int:h_id>", views.h_info, name="h_info"),
    path("odvoz", views.odvoz, name="odvoz"),
    path("permissionNG", views.permissionNG, name="permissionNG"),
    

    # functions
    path("done", views.done, name="done"),
    path("countBaliky", views.countBaliky, name="countBaliky"),
    path('needMaterial', views.needMaterial, name="needMaterial"),
    path('needOdvoz', views.needOdvoz, name="needOdvoz"),
    path('getOdvoz', views.getOdvoz, name="getOdvoz"),
    path('check', views.check, name="check"),
    path('odpad', views.odpad, name="odpad"),
    path('h/<int:h_id>/pdf_export', views.pdf_export, name="pdf_export"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/views.py
# import needed modules
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, FileResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .groups import group_required
from .models import Rozmitacka, Hoblovani, Baliky
from reportlab.pdfgen import canvas
import io

### FUNCTIONS IN THIS FILE ### 

# get all the models for the navbar and sort them
# so that it can display 10 latest orders from each
def update_models():
    global rozmitacka_model
    global hoblovani_model
    rozmitacka_model = Rozmitacka.objects.all().filter(do_vyroby=True)
    hoblovani_model = Hoblovani.objects.all().filter(do_vyroby=True)

# Create your views here.

### PAGES ###

# check if user is logged in and if not, redirect to login page
@login_required
def index(request):
    update_models()
    # show the index page and paste the models
    return render(request, "orders/index.html", {
        "rozmitacka": rozmitacka_model,
        "hoblovani": hoblovani_model,
    })

@login_required
@group_required('Rozmitac', 'Admin', 'Vozickar')
def r_info(request, r_id):
    update_models()
    # shows info for a particular rozmitacka order
    info = Rozmitacka.objects.get(id=r_id)
    return render(request, 'orders/r_info.html', {
        "order": info,
        "rozmitacka": rozmitacka_model,
        "hoblovani": hoblovani_model,
        "table": "r",
    })
@login_required
@group_required('Hoblovac', 'Admin', 'Vozickar')
def h_info(request, h_id):
    update_models()
    # shows info for a particular hoblovani order
    info = Hoblovani.objects.get(id=h_id)
    return render(request, 'orders/h_info.html', {
        "order": info,
        "rozmitacka": rozmitacka_model,
        "hoblovani": hoblovani_model,
        "table": "h",
    })

def login_view(request):
    if request.method == "POST":
        # gets the username and password
        username = request.POST["username"]
        password = request.POST["password"]
        #checks if the username and password are correct
        user = authenticate(request, username=username, password=password)
        if user is not None:
            # logs the user in and redirects to the index page
            login(request, user)
            return HttpResponseRedirect(reverse("orders:index"))
        else:
            # invalid credentials error
            return render(request, "orders/login.html", {
                "message": "Špatné přihlašovací údaje",
                "bad": "yes",
            })
    return render(request, "orders/login.html")

def logout_view(request):
    # logs the user out
    logout(request)
    return render(request, "orders/login.html",{
        "message": "You've been logout.",
        "good": "yes",
    })
@login_required
@group_required('Vozickar', 'Admin')
def odvoz(request):
    update_models()
    return render(request, "orders/odvoz.html", {
        "rozmitacka": rozmitacka_model,
        "hoblovani": hoblovani_model,
    })

def permissionNG(request):
    update_models()
    return render(request, "orders/permissionNG.html", {
        "rozmitacka": rozmitacka_model,
        "hoblovani": hoblovani_model,
    })

### FUNCTIONS ###

# this function makes the "done" attribute of order True
def done(request):
    update_models()
    if request.method == "POST":
        # extract the variables
        id = request.POST["id"]
        table = request.POST["table"]
        counter = int(request.POST["counter"])
        # check which table is it
        if table == "r":
            r = Rozmitacka.objects.get(id=id)
        elif table == "h":
            r = Hoblovani.objects.get(id=id)
        else:
            return JsonResponse({"code": 500})
        # change the hotovo value for the order to "True"
        r.hotovo = True
        if counter == 0:
            if r.baliky_celkem == 0:
                Baliky.objects.create(rozmitacka=r, ks=r.ks, done=True)
        r.save()
        # return successful http response
        return JsonResponse({"code": 400})


def countBaliky(request):
    update_models()
    if request.method == "POST":
        # extract the variables
        baliky = request.POST["baliky"]
        id = request.POST["id"]
        table = request.POST["table"]
        done = request.POST["d"]
        # check which tables
        if table == "r":
            r = Rozmitacka.objects.get(id=id)
            balik, _ = Baliky.objects.get_or_create(rozmitacka=r, done=False)
        elif table == "h":
            r = Hoblovani.objects.get(id=id)
            balik, _ = Baliky.objects.get_or_create(hoblovani=r, done=False)
        else:
            return JsonResponse({"code": 500})
        # change the number to the counter variable
        balik.ks = baliky
        if done == 'true':
            balik.done = True
        balik.save()
        return JsonResponse({"code": 400})

# this function changes order's field "get_material" to True if it's called
def needMaterial(request):
    update_models()
    if request.method == "POST":
        # extract the variables
        order_id = request.POST["order_id"]
        table = request.POST["table"]
        # get the right table and change the variable to True
        if table == "r":
            order = Rozmitacka.objects.get(id=order_id)
            order.get_material = True
            order.save()
        elif table == "h":
            order = Hoblovani.objects.get(id=order_id)
            order.get_material = True
            order.save()
        else:
            pass

    return HttpResponse(f"{order_id} from {table} - was succesfull")

def needOdvoz(request):
    update_models()
    if request.method == "POST":
        order_id = request.POST["order_id"]
        table = request.POST["table"]
        if table == "r":
            order = Rozmitacka.objects.get(id=order_id)
            order.get_zbytek = True
            order.save()
        elif table == "h":
            order = Hoblovani.objects.get(id=order_id)
            order.get_zbytek = True
            order.save()
        else:
            pass

    return HttpResponse(f"{order_id} from {table} - was succesfull")

def odpad(request):
    update_models()
    if request.method == "POST":
        order_id = request.POST["order_id"]
        table = request.POST["table"]
        if table == "r":
            order = Rozmitacka.objects.get(id=order_id)
            order.odpad = True
            order.save()
        elif table == "h":
            order = Hoblovani.objects.get(id=order_id)
            order.odpad = True
            order.save()
        else:
            pass

    return HttpResponse(f"{order_id} from {table} - was succesfull")

def getOdvoz(request):
    update_models()
    if request.method == "GET":
        r_odvoz = Rozmitacka.objects.filter(get_zbytek=True).filter(do_vyroby=True)
        r_odvoz_list = [order.id for order in r_odvoz]
        h_odvoz = Hoblovani.objects.filter(get_zbytek=True).filter(do_vyroby=True)
        h_odvoz_list = [order.id for order in h_odvoz]

        r_dovoz = Rozmitacka.objects.filter(get_material=True).filter(do_vyroby=True)
        r_dovoz_list = [order.id for order in r_dovoz]
        h_dovoz = Hoblovani.objects.filter(get_material=True).filter(do_vyroby=True)
        h_dovoz_list = [order.id for order in h_dovoz]

        r_odpad = Rozmitacka.objects.filter(odpad=True).filter(do_vyroby=True)
        r_odpad_list = [order.id for order in r_odpad]
        h_odpad = Hoblovani.objects.filter(odpad=True).filter(do_vyroby=True)
        h_odpad_list = [order.id for order in h_odpad]
        return JsonResponse({"r_odvoz":r_odvoz_list,
                            "h_odvoz":h_odvoz_list, 
                            "r_dovoz": r_dovoz_list, 
                            "h_dovoz": h_dovoz_list,
                            "r_odpad": r_odpad_list,
                            "h_odpad": h_odpad_list,})
    elif request.method == "POST":
        order_id = request.POST["id"]
        table = request.POST["table"]
        DorO = table.split("+")[1]
        table = table.split("+")[0]
        order_id = int(order_id.split("d")[1])
        if DorO == "odvoz":
            if table == "r":
                order = Rozmitacka.objects.get(id=order_id)
                order.get_zbytek = False
                order.save()
            elif table == "h":
                order = Hoblovani.objects.get(id=order_id)
                order.get_zbytek = False
                order.save()
        elif DorO == "dovoz":
            if table == "r":
                order = Rozmitacka.objects.get(id=order_id)
                order.get_material = False
                order.save()
            elif table == "h":
                order = Hoblovani.objects.get(id=order_id)
                order.get_material = False
                order.save()
        elif DorO == "odpad":
            if table == "r":
                order = Rozmitacka.objects.get(id=order_id)
                order.odpad = False
                order.save()
            elif table == "h":
                order = Hoblovani.objects.get(id=order_id)
                order.odpad = False
                order.save()
        return JsonResponse({"code":400})

def check(request):
    if request.method == "POST":
        table = request.POST["table"]
        id = request.POST["id"]
        if table == 'r':
            order = Rozmitacka.objects.get(id=id)
        elif table == 'h':
            order = Hoblovani.objects.get(id=id)
        return JsonResponse({
            "get_material": order.get_material,
            "get_zbytek": order.get_zbytek,
            "odpad": order.odpad,
            })

# PDF export
def pdf_export(request, h_id):
    buffer = io.BytesIO()
    x = canvas.Canvas(buffer)
    x.drawString(100, 100, "Let's generate this pdf file.")
    x.showPage()
    x.save()
    buffer.seek(0)

orders/templates/orders/index.html
{% extends "orders/layout.html" %}
{% load custom_tags %}
{% load static %}

{% block head %}
<title>Orders</title>
<!-- My own CSS -->
<link rel="stylesheet" href="{% static 'css/index.css'%}">
{% endblock %}


<!-- refresh button -->
{% block button %}
<button type="button" class="btn btn-primary btn-square-xl" style="margin-top: 5vh; margin-left: 2vw;" id="refresh" onClick="window.location.reload()" >Refresh</button>
{% endblock %}


{% block body %}

{% if not request.user|has_group:"Vozickar" %}
<div id="index-button">
  <button type="button" id="refresh" onClick="window.location.reload()" class="btn btn-primary btn-square-xl" >Refresh</button>
</div>
{% endif %}


<!-- .table-wrap changes the height of the table!!!-->
{% if request.user|has_group:"Rozmitac" %}
<div class="container px-3 my-5 clearfix ">
    <!-- Rozmitacka table -->
    <div class="card">
        <div class="card-header">
            <h1>Rozmítačka</h1>
        </div>
        <div class="card-body">
            <div class="table-responsive table-wrap">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="width: fit-content;">Zákazník</th>
                    <th class="text-center py-3 px-4" style="width: fit-content;">Požadované datum výroby</th>
                    <th class="text-center py-3 px-4" style="width: fit-content;">Hotovo</th>
                    <!--<th class="text-right py-3 px-4" style="width: fit-content;">Kontrola</th>-->
                    <th class="text-center py-3 px-4" style="width: fit-content;">Detaily</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in rozmitacka %}
                {% if not order.kontrola %}
                    <tr>
                    <td class="p-4">
                        <div class="media align-items-center">
                        <div class="media-body">
                            <a href="{% url 'orders:r_info' order.id %}" class="d-block text-dark">{{order.zakaznik}}
                              {% if order.modrin %}
                              <p class="fa fa-tree" style="color: blue;"></p>
                              {% endif %}
                            </a>
                            <small>
                            <span class="text-muted">{{ order.jednotky }} hotovo:</span>
                            {{order.ks_hotovo}}/{{order.ks}} &nbsp;
                            <span class="text-muted">Poznámka: </span> {{order.poznamka}} &nbsp;
                            <span class="text-muted">Rozměry: </span> {{order.rozmery}}
                            </small>
                        </div>
                        </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{order.pozadovane_datum_vyroby}}</td>
                    <td class="text-right font-weight-semibold align-middle p-4">
                        {% if order.hotovo %}
                        <i class="bi bi-check-circle-fill"></i>
                        {% else %}
                        <i class="bi bi-x-circle-fill"></i>
                        {% endif %}
                    </td>
                    <!--<td class="text-right font-weight-semibold align-middle p-4">
                        {% if order.kontrola %}
                        <i class="bi bi-check-circle-fill"></i>
                        {% else %}
                        <i class="bi bi-x-circle-fill"></i>
                        {% endif %}
                    </td>-->
                    <td class="text-right font-weight-semibold align-middle p-4"><a href="{% url 'orders:r_info' order.id %}"><i class="bi bi-arrow-right-circle-fill"></i></a></td>
                    </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- / Rozmitacka table -->
      </div>
  </div>
</div>
{% endif %}

{% if request.user|has_group:"Hoblovac" %}
<div class="container px-3 my-5 clearfix">
    <!-- Hoblovani table -->
    <div class="card">
        <div class="card-header">
            <h1>Hoblování</h1>
        </div>
        <div class="card-body">
            <div class="table-responsive table-wrap">
              <table class="table table-bordered m-0">
                <thead>
                  <tr>
                    <!-- Set columns width -->
                    <th class="text-center py-3 px-4" style="width: fit-content;">Zákazník</th>
                    <th class="text-center py-3 px-4" style="width: fit-content;">Požadované datum výroby</th>
                    <th class="text-center py-3 px-4" style="width: fit-content;">Hotovo</th>
                    <!--<th class="text-right py-3 px-4" style="width: fit-content;">Kontrola</th>-->
                    <th class="text-center py-3 px-4" style="width: fit-content;">Detaily</th>
                  </tr>
                </thead>
                <tbody>
                {% for order in hoblovani %}
                {% if not order.kontrola %}
                    <tr>
                    <td class="p-4">
                        <div class="media align-items-center">
                        <div class="media-body">
                            <a href="{% url 'orders:h_info' order.id %}" class="d-block text-dark">{{order.zakaznik}}
                              {% if order.modrin %}
                              <p class="fa fa-tree" style="color: blue;"></p>
                              {% endif %}
                            </a>
                            <small>
                            <span class="text-muted">{{ order.jednotky }} hotovo:</span>
                            {{order.ks_hotovo}}/{{order.ks}} &nbsp;
                            <span class="text-muted">Poznámka: </span> {{order.poznamka}} &nbsp;
                            <span class="text-muted">Rozměry: </span> {{order.rozmery}}
                            </small>
                        </div> 
                        </div>
                    </td>
                    <td class="text-right font-weight-semibold align-middle p-4">{{order.pozadovane_datum_vyroby}}</td>
                    <td class="text-right font-weight-semibold align-middle p-4">
                        {% if order.hotovo %}
                        <i class="bi bi-check-circle-fill"></i>
                        {% else %}
                        <i class="bi bi-x-circle-fill"></i>
                        {% endif %}
                    </td>
                    <!--<td class="text-right font-weight-semibold align-middle p-4">
                        {% if order.kontrola %}
                        <i class="bi bi-check-circle-fill"></i>
                        {% else %}
                        <i class="bi bi-x-circle-fill"></i>
                        {% endif %}
                    </td>-->
                    <td class="text-right font-weight-semibold align-middle p-4"><a href="{% url 'orders:h_info' order.id %}"><i class="bi bi-arrow-right-circle-fill"></i></a></td>
                    </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- / Hoblovani table -->
      </div>
  </div>
</div>
{% endif %}
{% endblock %}

orders/templates/orders/layout.html
{% load custom_tags %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- Bootstrap CSS and JS -->
        <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Icons -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <!-- Add Ajax -->
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
        <!-- My own CSS -->
        <link rel="stylesheet" href="{% static 'css/layout.css'%}">
        <!-- My own JS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


        <script>
          var URLgo = "{% url 'orders:getOdvoz' %}";
        </script>

        {% block head %}
        {% endblock %}
    </head>
    <body>
      <!-- changed navbar-expand-lg to navbar-expand -->
        <nav class="navbar sticky-top navbar-expand navbar-light bg-light" style="padding-left:1vw">
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <span class="navbar-brand" href="">{{ request.user.username }}</span>
          
            <div class="collapse navbar-collapse" id="navbar">
              <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'orders:index' %}">Domů</a>
                </li> 
                {% if user.is_authenticated %}
                {% if request.user|has_group:"Rozmitac" %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Rozmítačka
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for order in rozmitacka|slice:":10" %}
                        <a class="dropdown-item" href="{% url 'orders:r_info' order.id %}">{{ order.zakaznik }}
                          {% if order.modrin %}
                          <p class="fa fa-tree" style="color: blue;"></p>
                          {% endif %}
                          - {{ order.pozadovane_datum_vyroby }}</a>
                        {% endfor %}
                    </div>
                  </li>
                  {% endif %}
                  {% if request.user|has_group:"Hoblovac" %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Hoblování
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for order in hoblovani|slice:":10" %}
                        <a class="dropdown-item" href="{% url 'orders:h_info' order.id %}">{{ order.zakaznik }}
                          {% if order.modrin %}
                          <p class="fa fa-tree" style="color: blue;"></p>
                          {% endif %}
                          - {{ order.pozadovane_datum_vyroby }}</a>
                        {% endfor %}
                    </div>
                  </li>
                  {% endif %}
                  {% if request.user|has_group:"Vozickar" %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'orders:odvoz' %}">Dovoz a Odvoz</a>
                  </li>
                  <li class="nav-item">
                    <button type="button" class="btn btn-danger" onclick="attention = false; document.body.style.background = '#eee'; localStorage.setItem('attention', 'false')">Vidím</button>
                  </li>
                  {% endif %}
                  
                  {% if request.user.is_staff %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}
                {% endif %}
              </ul>
              <ul class="navbar-nav ms-auto" style="margin-right: 10px">
                <li class="nav-item">
                    <a href="{% url 'orders:logout' %}" class="nav-link">Odhlásit se</a>
                  </li>
              </ul>
              <!--<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>-->
          </nav>

          <!--{% if user.is_superuser %}
          <div id="index-button">
            <button type="button" id="refresh" onClick="window.location.reload()" class="btn btn-primary btn-square-xxl" >Refresh</button>
          </div>
          {% endif %}-->
        {% if good %}
        <div class="row">
        <div class="mx-auto">
            <div class="alert alert-success div-style alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
        
        {% elif bad %}
        <div class="col-md-10 col-md-offset-1">
            <div class="alert alert-danger div-style alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
        {% endif %}
        {% if request.user|has_group:"Vozickar" %}
        <div id="buttons">
          <button type="button" class="btn btn-danger btn-square-xl" style="margin-top: 5vh; margin-right: 2vw;" onclick="attention = false; document.body.style.background = '#eee'; localStorage.setItem('attention', 'false')">Vidím</button>
          {% block button %}
          {% endblock %}
        </div>
        {% endif %}
        {% block body %}
        {% endblock %}
    </body>
</html>
<script>
  // set all jinja2 variables to use in all functions
  let counter = {{ order.ks_hotovo }};
  let baliky_celkem = {{ order.baliky_celkem }};
  let last_balik = {{ order.last_balik }}
  var id = {{ order.id }};
  var table = "{{ table }}";
  var URLd = "{% url 'orders:done' %}";
  var ks = {{ order.ks }};
  var URLno = "{% url 'orders:needOdvoz' %}";
  var URLcb = "{% url 'orders:countBaliky' %}";
  var URLnm = "{% url 'orders:needMaterial' %}";
  var URLo = "{% url 'orders:odpad' %}";
</script>
<script type="text/javascript" src="{% static 'js/layout.js' %}"></script>
{% if request.user|has_group:"Vozickar" %}
<script>
  $(document).ready(function(){
    var c_visible = localStorage.getItem("c_visible");
    var flash;
    if (localStorage.getItem("attention") == "true") {
      attention = true;
    } else if (localStorage.getItem("attention") == "false") {
      attention = false;
    };
    // create a reccuring function
    setInterval(function(){
        // get the orders, that need to get rid of material
        $.ajax({
            type:'GET',
            url: URLgo,
            success: function(response){
                // set the variables to the results from the GET method
                r_odvoz = response.r_odvoz
                h_odvoz  = response.h_odvoz
                r_dovoz = response.r_dovoz
                h_dovoz = response.h_dovoz
                r_odpad = response.r_odpad
                h_odpad = response.h_odpad
                visible = r_odvoz.length + h_odvoz.length + r_dovoz.length + h_dovoz.length + r_odpad.length + h_odpad.length
                // check if the visible and c_visible arrays are the same and if the arrays are not empty
                if (visible != c_visible) {
                        attention = true;
                        localStorage.setItem("c_visible", visible.toString())
                        localStorage.setItem("attention", "true")
                }
                // if a table has something inside it, flash the screen
                if (r_odvoz.length != 0 || h_odvoz.length != 0 || r_dovoz.length != 0 || h_dovoz.length != 0 || r_odpad.length != 0 || h_odpad.length != 0) {
                    if (attention == true) {
                        if (flash == true) {
                            document.body.style.background = "#FF0000"
                            flash = !flash;
                        }else {
                            document.body.style.background = "#eee"
                            flash = !flash;
                        }
                    }
                }
                c_visible = visible;
            }
        });
    },500);
});
</script>
{% endif %}

orders/templates/orders/login.html
{% extends "orders/layout.html" %}
{% load custom_tags %}
{% load static %}

{% block head %}
<title>Login</title>
<!-- My own CSS -->
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div class="row">
	<aside class="col-sm-4 mx-auto">

<div class="card">
    {% if form.errors %}
    <p>Omlouváme se, vaše uživatelské jméno a heslo se neshodují. Prosím zkuste to znovu.</p>
  {% endif %}
<article class="card-body">
<!--<a href="" class="float-right btn btn-outline-primary">Sign up</a> -->
<h4 class="card-title mb-4 mt-1">Přihlásit se</h4>
<form action="{% url 'orders:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
    	<label>Vaše uživatelské jméno:</label>
        <input name="username" class="form-control" placeholder="Uživatelské jméno" type="Username">
    </div> <!-- form-group// -->
    <div class="form-group">
    	<label>Vaše heslo:</label>
        <input name="password" class="form-control" placeholder="********" type="password">
    </div> <!-- form-group// --> 
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> Přihlásit se  </button>
    </div> <!-- form-group// -->                                                           
</form>
</article>
</div> <!-- card.// -->



{% endblock %}

orders/templates/orders/permissionNG.html
{% extends "orders/layout.html" %}
{% load custom_tags %}
{% load static %}

{% block head %}
<title>Tabulka</title>
{% endblock %}

{% block body %}
<h1 style="text-align: center; margin-top:20%;">Neoprávněný vstup, prosím požádejte administrátora o vstup</h1>
{% endblock %}